<a href="https://colab.research.google.com/github/dmtrung14/pyTorch_fundamentals/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Tensors


In [ ]:
###scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim 

0

In [ ]:
scalar.item()


7

In [ ]:
### vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
### matrix
matrix = torch.tensor([[7,7],[8,8]])
matrix

tensor([[7, 7],
        [8, 8]])

In [ ]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [ ]:
### Tensor

TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


This means one dimension of 3 by 3, 3 dimensions of 1 by 3, and 3 scalars in the inner most bracket.

## Random Tensors

Random tensors are important because many neural networks will start with a random tensor of desired dimensions, then adjust those random numbers to better represent the data. 

In [ ]:
### Create random tensors of size/shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3838, 0.5322, 0.4797, 0.0418],
        [0.3637, 0.1763, 0.5980, 0.2447],
        [0.6658, 0.0835, 0.0854, 0.4734]])

In [ ]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([2, 1, 3])


## Tensors of Zeroes and Ones

What if we want to create a tensor of zeroes and ones, maybe something like a boolean tensor?

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range of Tensors and Tensors-like

Use ```torch.range()``` will return deprecated message, so use ```torch.arange()``` instead

In [ ]:
# Create a range
one_to_ten = torch.arange(start = 1, end = 21, step = 2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Type

The default data type of tensors is ```float32``` but what about the other things?

**Notes:** Tensor datatypes is one the 3 big errors you'll run into with PyTorch & deep learning: 
1. Tensors not right datatype
2. Tensors not right shape (matrix multiplication for instance)
3. Tensors not on the right device (CPU or smth)

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float32)
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.dim

<function Tensor.dim>

In [ ]:
# Learn Device
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad = False)

+ dtype = what the data type is (default =
float32, but can set to others like the example above) 

Why? to prioritize computing speed or precision.

+ device = `"cpu", "cuda", "gpu"`... . We will need tensors to be stored on the same computing device (CPU, CUDA, GPU, etc.) to perform computations

+ requires_grad = (require gradients) track gradient when it goes through certain computations.




In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_64_tensor = float_16_tensor.type(torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
temp = float_16_tensor * float_32_tensor
temp, temp.dtype

(tensor([ 9., 36., 81.]), torch.float32)

torch.Size([3])

### Side notes on multiple matrix multiplication functions in PyTorch

- The default multiplication is element-wise multiplication: ```[a_1, b_1][c_1, d_1] = [a_1b_1, c_1d_1]```
- Other multiplications requires Torch functions:
  - ``` torch.kron``` : for Kronecker product
  - ```torch.matmul```: for matrix multiplication

In [ ]:
e1 = torch.rand(1,1,2)
e2 = torch.rand(2,3,3)
torch.kron(e1, e2)

tensor([[[0.1836, 0.2485, 0.1502, 0.0624, 0.0845, 0.0510],
         [0.1541, 0.1922, 0.1412, 0.0524, 0.0653, 0.0480],
         [0.1970, 0.1677, 0.1453, 0.0670, 0.0570, 0.0494]],

        [[0.0617, 0.0621, 0.3471, 0.0210, 0.0211, 0.1180],
         [0.1132, 0.2384, 0.1851, 0.0385, 0.0810, 0.0629],
         [0.3607, 0.0263, 0.2520, 0.1226, 0.0089, 0.0856]]])

## Manipulating Tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise , as noted above)
* Division
* Matrix multiplication

In [ ]:
# Tensor addition
tensor = torch.tensor([1,2,3])
tensor + 10, tensor + torch.tensor([1,2,3])

(tensor([11, 12, 13]), tensor([2, 4, 6]))

In [ ]:
#tensor multiplication
tensor = torch.tensor([1,2,3])
tensor = tensor * 10
print(tensor)

#tensor subtraction
tensor -= 5
print(tensor)

tensor([10, 20, 30])
tensor([ 5, 15, 25])


One of the most common errors in deep learning is shape errors.

## Finding the Min, Max, Mean, Sum, etc. (Tensor aggregation)

In [ ]:
## Create a tensor
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the min and the max:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
# Using methods of x:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
#Find the mean
x = x.type(torch.float32)
x.mean()

tensor(45.)

**Notes:** Ok but if we try to use mean on any random tensor, we will probably get some error like this: 
```
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
```

Therefore, it is neccessary that we convert x to its appropriate type, in this case a float, and we choose one precision, so `x = x.type(torch.float32)`

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

### Finding the positional min and max

In [ ]:
x.argmin(), x.argmax() # Find the position in tensor that has the minimum value with argmin() -> return index position of the minimum element of the array

(tensor(0), tensor(9))

Let's play around with it for a while shall we?

In [ ]:
x1 = torch.rand(2,3)
x1, x1.argmin(), x1.argmax(), x1.type(torch.float32).mean()

(tensor([[0.7169, 0.2678, 0.4956],
         [0.0985, 0.6351, 0.3671]]),
 tensor(3),
 tensor(0),
 tensor(0.4302))

## Reshaping, Stacking, Squeezing, Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack). `torch.stack`: https://pytorch.org/docs/stable/generated/torch.stack.html, then let's google the same `torch.hstack()` and `torch.vstack()`
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of input with dimensions permuted (swapped) in a certain way



In [ ]:
# Let's create a tensor
import torch
x = torch.arange(0., 10.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape
# So the original matrix is [a*b], then the reshape method will take this a*b elements to map it into a new matrix of dimension c*d. Therefore, a*b = c*d

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 torch.Size([2, 5]))

In [ ]:
# Change the view
z = x.view(10, 1)
z, z.shape, x

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# changing x changes x because view of a tensor shares the same memory as the original tensor, so: 
z[0] = 5
z,x

(tensor([[5.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x])
print(x_stacked, x_stacked.shape)
# The default option is to stack the tensors on each other, i.e. dim = 0
x_stacked_horizontal = torch.stack([x,x,x], dim = 1)
print(x_stacked_horizontal, x_stacked_horizontal.shape)

tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([3, 10])
tensor([[5., 5., 5.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]]) torch.Size([10, 3])


In [ ]:
# squeeze: remove all dimensions with only 1 element
y_expanded = torch.rand(2,1,3)
y_squeezed = y_expanded.squeeze()
y_squeezed, y_squeezed.shape

(tensor([[0.3825, 0.5991, 0.5667],
         [0.4262, 0.6440, 0.7001]]),
 torch.Size([2, 3]))

In [ ]:
y_unsqueezed_0 = y_squeezed.unsqueeze(dim = 0)
y_unsqueezed_1 = y_squeezed.unsqueeze(dim = 1)
y_unsqueezed_0, y_unsqueezed_0.shape, y_unsqueezed_1, y_unsqueezed_1.shape

(tensor([[[0.3825, 0.5991, 0.5667],
          [0.4262, 0.6440, 0.7001]]]),
 torch.Size([1, 2, 3]),
 tensor([[[0.3825, 0.5991, 0.5667]],
 
         [[0.4262, 0.6440, 0.7001]]]),
 torch.Size([2, 1, 3]))

In [ ]:
#torch.permute -rearranges the dimensions of a target tensor in a specified manner
x = torch.rand(2,3,4)
x, torch.permute(x, (1,2,0))

(tensor([[[0.6955, 0.2387, 0.9605, 0.7970],
          [0.3580, 0.8134, 0.7609, 0.7544],
          [0.6029, 0.9305, 0.0765, 0.5659]],
 
         [[0.5059, 0.7672, 0.3522, 0.9212],
          [0.7197, 0.9252, 0.5921, 0.7286],
          [0.8556, 0.1377, 0.5048, 0.8365]]]),
 tensor([[[0.6955, 0.5059],
          [0.2387, 0.7672],
          [0.9605, 0.3522],
          [0.7970, 0.9212]],
 
         [[0.3580, 0.7197],
          [0.8134, 0.9252],
          [0.7609, 0.5921],
          [0.7544, 0.7286]],
 
         [[0.6029, 0.8556],
          [0.9305, 0.1377],
          [0.0765, 0.5048],
          [0.5659, 0.8365]]]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
#two ways to indexing tensors: x[a,b,c] or x[a][b][c]. Where a,b,c are the dimensions, from the outer most in
x, x.shape, x[0,1,0], x[0][1][0],  x[0,1,0] == x[0][1][0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 tensor(4),
 tensor(4),
 tensor(True))

Sounds similar to Python? But what if we are trying to extract a column of the matrix, i.e. we want a certain index of the second dimension : accessing certain indices of the third dimension without having to access it? 

In [ ]:
x[:, : , 1] # accessing all values of the 0th and 1st dimensions but only index 1 of 2nd dimension, or:
x[:, 1, 1] #accessing all values of the 0th dimensions but only index 1 of 1st and 2nd dimension
x[:, 1, :] #note how this does not quite matter much (as we might as well write x[:,1])
x[:,1] == x[:,1, :], x[:,1].shape == x[:,1,:].shape

(tensor([[True, True, True]]), True)

## PyTorch Tensors and NumPy

Numpy is a popular scientific Python numerical computing library. 

And because of this, PyTorch has functionality to interact with it. 

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #numpy default dtype = float64 therefore we SHOULD convert (not mandatory though)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
# Let's see what happens to `tensor` when we change the values of `array`?
array = array +1
array, tensor
## --> it does not change the value of tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))